language: node_js

node_js:
  - 12.14

sudo: false

after_script:
  - npm run coveralls

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

script:
  - npm start -- --silent &
  - npm run cy:run --
  - kill $(jobs -p) || true
